# This is a basic workflow to help you get started with Actions

name: mercuryhealth-web-ci

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.6.0
      with:
        Dotnet-version: 3.1.101
      
    - run: dotnet build -c Release
    - run: dotnet test -c Release
    - run: dotnet publish -c Release -o mercuryhealth-we

    - name: Deploy to Azure
      uses: Azure/webapps-deploy@v1
      with:
        publish-profile: ${{ secrets.AzureWebAppPublishProfile }}
        package: ./mercuryhealth-we
